"""
model.py — Temporal Transformer for Thermal Comfort (T3C)
==========================================================

Architecture Overview (see Figure 1 in the paper):

    Input: X ∈ ℝ^{B × T × D}     (batch × 12 timesteps × 17 features)
                ↓
    Linear Projection (17 → 256)
                ↓
    + Learnable Positional Embedding
                ↓
    Transformer Encoder Stack (6 layers)
      ├── Multi-Head Self-Attention (8 heads)
      ├── Add & Norm
      ├── Feedforward Network (256 → 512 → 256, ReLU)
      └── Add & Norm
                ↓
    Last-Token Pooling (extract t=11, the real observation)
                ↓
    Dropout (0.1) → Linear Classifier (256 → 3)
                ↓
    Output: logits ∈ ℝ^{B × 3}   → Softmax → {N, UW, UC}

Design Decisions:
    - Learnable positional embeddings (not sinusoidal) because the sequence
      length is short and fixed (T=12). Sinusoidal encoding is better suited
      for variable-length sequences in NLP; here, learned embeddings allow
      the model to discover task-specific temporal patterns.

    - Last-token pooling (not mean pooling) because the final timestep
      contains the actual survey data. Earlier timesteps are synthetic
      history generated by PISSG. The model should ground its prediction
      on the real observation while using attention to incorporate context.

    - Training-time jitter (Gaussian noise with σ=0.005) acts as a
      regularizer, preventing the model from overfitting to the exact
      noise patterns generated by PISSG during data preparation.

    - LayerNorm after embedding + positional encoding stabilizes training
      by normalizing the input distribution before the attention layers.

Reference: Paper Section 3, Figure 1, Section 5.4.
"""

import torch
import torch.nn as nn
import math
from typing import Optional

import sys
sys.path.append("..")
from config import ModelConfig, TrainConfig


class ComfortTransformer(nn.Module):
    """
    T3C: Temporal Transformer for Thermal Comfort.

    A Transformer encoder that processes PISSG-generated temporal sequences
    of environmental conditions and predicts 3-class thermal comfort.

    Parameters
    ----------
    model_cfg : ModelConfig
        Architecture hyperparameters (d_model, nhead, num_layers, etc.).
    jitter_std : float
        Standard deviation of Gaussian noise applied during training
        for data augmentation (default: 0.005).
    """

    def __init__(
        self,
        model_cfg: Optional[ModelConfig] = None,
        jitter_std: float = 0.005,
    ):
        super().__init__()

        if model_cfg is None:
            model_cfg = ModelConfig()

        self.jitter_std = jitter_std

        # --- 1. Feature Projection ---
        # Project raw 17-dim features into the Transformer's d_model space.
        # This linear layer learns which feature combinations are most
        # informative for each attention head.
        self.embedding = nn.Linear(model_cfg.input_dim, model_cfg.d_model)

        # --- 2. Learnable Positional Embedding ---
        # Each of the 12 timestep positions gets a learned embedding vector.
        # Initialized to zeros; the model learns temporal position semantics
        # during training (e.g., "recent" vs. "distant" history).
        self.pos_embedding = nn.Parameter(
            torch.zeros(1, model_cfg.seq_length, model_cfg.d_model)
        )

        # --- 3. Pre-attention Layer Normalization ---
        # Stabilizes training by normalizing the combined embedding before
        # it enters the attention layers.
        self.input_norm = nn.LayerNorm(model_cfg.d_model)

        # --- 4. Transformer Encoder Stack ---
        # 6 layers × 8 heads = 48 parallel attention patterns.
        # Each head can specialize (e.g., one head tracks temperature drift,
        # another monitors humidity–velocity interactions).
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=model_cfg.d_model,
            nhead=model_cfg.nhead,
            dim_feedforward=model_cfg.dim_feedforward,
            dropout=model_cfg.dropout,
            batch_first=True,  # Input shape: (batch, seq, features)
        )
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=model_cfg.num_layers,
        )

        # --- 5. Classification Head ---
        # Last-token output → dropout → linear → 3 class logits
        self.dropout = nn.Dropout(model_cfg.dropout)
        self.classifier = nn.Linear(model_cfg.d_model, model_cfg.num_classes)

    def forward(self, x: torch.Tensor, augment: bool = False) -> torch.Tensor:
        """
        Forward pass through the T3C model.

        Parameters
        ----------
        x : torch.Tensor
            Input tensor of shape (batch_size, seq_length, input_dim).
            Generated by PISSG: 12 timesteps × 17 features.
        augment : bool
            If True and model is in training mode, apply Gaussian jitter
            as a regularization technique. Should be False during
            validation and testing.

        Returns
        -------
        logits : torch.Tensor
            Raw class scores of shape (batch_size, num_classes).
            Apply softmax or argmax for predicted class.
        """
        # --- Training-time augmentation ---
        # Small Gaussian noise prevents overfitting to PISSG's specific
        # noise patterns. Disabled during validation/testing.
        if self.training and augment:
            noise = torch.randn_like(x) * self.jitter_std
            x = x + noise

        # --- Embedding + Positional encoding ---
        x = self.embedding(x)          # (B, T, D) → (B, T, d_model)
        x = x + self.pos_embedding     # Add learned temporal signal
        x = self.input_norm(x)         # Normalize before attention

        # --- Transformer encoder ---
        x = self.transformer_encoder(x)  # (B, T, d_model)

        # --- Last-token pooling ---
        # Extract the representation at t=seq_length-1 (the real observation).
        # The attention mechanism has already aggregated information from all
        # 12 timesteps into this position.
        x = x[:, -1, :]               # (B, d_model)

        # --- Classifier ---
        x = self.dropout(x)
        logits = self.classifier(x)    # (B, num_classes)

        return logits


def count_parameters(model: nn.Module) -> int:
    """Count the number of trainable parameters in the model."""
    return sum(p.numel() for p in model.parameters() if p.requires_grad)
